# Generated by Django 5.2.7 on 2025-12-29 00:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproyecto',
            name='imagen_galeria',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_galeria'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_portada'),
        ),
    ]
