# Generated by Django 5.2.7 on 2025-12-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En curso'), ('realizado', 'Realizado')], default='en_curso', max_length=20),
        ),
    ]
