# Generated by Django 5.2.7 on 2025-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En curso'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='en_curso', max_length=20),
        ),
    ]
