# Generated by Django 5.2.7 on 2025-11-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
