# Generated by Django 5.2.7 on 2025-12-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/imagen_portada')),
                ('estado', models.CharField(choices=[('proximo', 'Próximo'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='proximo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_galeria', models.ImageField(upload_to='eventos/galeria/')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='eventos.evento')),
            ],
        ),
    ]
