# Generated by Django 5.2.7 on 2025-12-29 00:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_portada'),
        ),
        migrations.AlterField(
            model_name='imagenevento',
            name='imagen_galeria',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_galeria'),
        ),
    ]
