# Generated by Django 5.2.7 on 2025-12-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_imagen_galeriaimagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/imagen_portada'),
        ),
        migrations.DeleteModel(
            name='GaleriaImagen',
        ),
    ]
