# Generated by Django 5.2.7 on 2025-12-10 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_imagen_delete_galeriaimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_galeria', models.ImageField(upload_to='eventos/galeria/')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='eventos.evento')),
            ],
        ),
    ]
