# Generated by Django 5.2.7 on 2025-12-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_imagenevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('proximo', 'Próximo'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='proximo', max_length=15),
        ),
    ]
