# Generated by Django 5.2.7 on 2025-11-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='fotos_perfil/default.png', upload_to='fotos_perfil/'),
        ),
    ]
