# Generated by Django 5.2.7 on 2026-01-08 07:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MujerReferente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('lugar_origen', models.CharField(max_length=150)),
                ('ocupacion', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mujer_referente')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
