# Generated by Django 5.2.7 on 2025-12-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres_referentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mujerreferente',
            old_name='activo',
            new_name='estado',
        ),
    ]
