# Generated by Django 5.2.7 on 2025-12-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('cargo', models.CharField(choices=[('presidenta', 'Presidenta'), ('secretaria', 'Secretaria'), ('tesorera', 'Tesorera'), ('socia', 'Socia')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='miembros/')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
